# Generated by Django 6.0.3 on 2026-03-11 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Free Starter Offer', max_length=200)),
                ('description', models.TextField(default='Get started for free — no payment needed!')),
                ('discount_text', models.CharField(blank=True, default='100% Free', max_length=100)),
                ('free_downloads_allowed', models.PositiveIntegerField(default=3, help_text='How many free PDF downloads each user gets while this offer is active')),
                ('ai_optimize_free', models.BooleanField(default=True, help_text='Allow free AI Optimize usage while this offer is active')),
                ('is_active', models.BooleanField(default=False, help_text='Only ONE offer should be active at a time. Toggle here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offer / Free Tier Config',
                'verbose_name_plural': 'Offers / Free Tier Configs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('downloads_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
