# Generated by Django 5.1.4 on 2026-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_promocode_alter_offer_id_alter_resume_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ats_reports_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
